name: Coverage

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  update-coverage:
    name: Update Coverage
    runs-on: ubuntu-latest
    container: nexishunter/docker_flutter
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Update the coverage
        run: |
          flutter test --coverage
          echo "$(cat ./coverage/lcov.info)"
      - name: Update Coveralls
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
