name: Coverage

on:
  push:
    branches:
      - main
      - 'ci/**'

jobs:
  unit-test:
    runs-on: ubuntu-latest
    name: Unit Tests
    steps:
      - name: Set up Java
        uses: actions/setup-java@v1
        with:
          java-version: '12.x'
      - name: Set up Flutter
        uses: subosito/flutter-action@v1
        with:
          channel: 'stable'
      - name: Switch Flutter to Master
        # Set up flutter on master channel to allow for desktop testing/building
        run: |
          flutter channel master
          flutter upgrade
          flutter config --enable-web --enable-linux-desktop
          flutter precache --{web,linux}

      - name: Checkout
        uses: actions/checkout@v1
      - name: Run Integration Tests
        run: |
          flutter pub get
          flutter test --coverage
      - name: Archive code coverage results
        uses: actions/upload-artifact@v2
        with:
          name: code-coverage
          path: coverage/lcov.info

  coverage:
    runs-on: ubuntu-latest
    needs: unit-test
    steps:
      - name: Coveralls
        uses: coverallsapp/github-action@v1.1.2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          path-to-lcov: ./coverage/lcov.info
          base-path: lib

#  update-coverage:
#    name: Update Coverage
#    runs-on: ubuntu-latest
#    container: nexishunter/docker_flutter
#    outputs:
#      coverage: ${{ steps.gen_covg.outputs.coverage }}
#    steps:
#      - name: Checkout
#        uses: actions/checkout@v2
#      - name: Update the coverage
#        run: |
#          flutter test --coverage --coverage-path=coverage.info
#          ls -la ./
#
#
##   publish:
##     name: Publish Coverage
##     runs-on: ubuntu-latest
##     needs: update-coverage
##     steps:
##      - name: Load Coverage
##        uses: actions/download-artifact@v2
##        with:
##          name: code-coverage
##      - name: Extract Coverage
##        run: |
##          unzip code-coverage
#      - name: Update Coveralls
#        uses: coverallsapp/github-action@master
#        with:
#          github-token: ${{ secrets.GITHUB_TOKEN }}
#          path-to-lcov: coverage.info
