name: Coverage

on:
  push:
    branches:
      - main
      - 'ci/**'

jobs:
  update-coverage:
    name: Update Coverage
    runs-on: ubuntu-latest
    container: nexishunter/docker_flutter
    outputs:
      coverage: ${{ steps.gen_covg.outputs.coverage }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Update the coverage
        id: gen_covg
        run: |
          flutter test --coverage
          COVERAGE=$(echo "$(cat ./coverage/lcov.info)")

          echo "::set-output name=coverage::${COVERAGE}"

  publish:
    name: Publish Coverage
    runs-on: ubuntu-latest
    needs: update-coverage
    steps:
      - name: Load Coverage
        run: |
          mkdir -p coverage
          echo ${{ needs.update-coverage.outputs.coverage }} >> ./coverage/lcov.info
      - name: Update Coveralls
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
