name: Coverage

on:
  push:
    branches:
      - main

jobs:
  update-coverage:
    name: Update Coverage
    runs-on: ubuntu-latest
    container: nexishunter/docker_flutter
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Update the coverage
        run: flutter test --coverage
      - name: Update Coveralls
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
