name: Coverage

on:
  push:
    branches:
      - main
      - 'ci/**'

jobs:
  update-coverage:
    name: Update Coverage
    runs-on: ubuntu-latest
    container: nexishunter/docker_flutter
    outputs:
      coverage: ${{ steps.gen_covg.outputs.coverage }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Update the coverage
        run: |
          mkdir -p coverage
          flutter test --coverage --coverage-path=coverage/lcov.info
          ls -la coverage/
      - name: Archive code coverage results
        uses: actions/upload-artifact@v2
        with:
          name: code-coverage.zip
          path: coverage/lcov.info

  publish:
    name: Publish Coverage
    runs-on: ubuntu-latest
    needs: update-coverage
    steps:
      - name: Load Coverage
        uses: actions/download-artifact@v2
        with:
          name: code-coverage.zip
      - name: Extract Coverage
        run: |
          unzip code-coverage.zip
      - name: Update Coveralls
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          path-to-lcov: lcov.info
